@host=https://3001-bronze-impala-vib65y6n.ws-us16.gitpod.io
#puedo definir variables, en este caso host
#para luego definir los metodos que quiero usar

### Creación de hash
POST {{host}}/hash
Content-Type: application/json
#aqui estoy llamando al endpoint hash de main.py 

### REGISTER
POST {{host}}/register
Content-Type: application/json

{
    "email":"conejitoreload@hola.cl",
    "nombre":"Conejito 2.0",
    "password":"conejito"
}

# {
#     "email":"la@guagua.cl",
#     "nombre":"guagua",
#     "password":"87654321"
# }




###  @AUTH
# @name authSession
POST {{host}}/login
Content-Type: application/json

{
    "email":"conejito@hola.cl",
    "password":"sdfs"
}

###
@token = {{authSession.response.body.$.token}}



### USER
GET {{host}}/users
Content-Type: application/json
#Authorization: Bearer {{token}}

#en este archivo deberian ir todas las formas 
#de inyectar cada uno de los endpoints

### DESAFIO POST
POST {{host}}/desafios
Content-Type: application/json

{
    "descripcionDesafio": "Leer mas",
    "dias del desafio": [],
    "feat1": "10",
    "feat2": "11",
    "feat3": "12",
    "nombreDesafio": "Desafio 4",
    "photoURL": "http://cdn2.dineroenimagen.com/media/dinero/styles/xlarge/public/images/2019/12/knowledge-10520101920.jpg"
    }

#los campos son en su mayoria unicos

### DIAS POST
POST {{host}}/dias
Content-Type: application/json

{
    "idDesafio": null,
    "idReceta": null,
    "idRutina": null,
    "numeroDia": 4
    }

### RUTINA POST
POST {{host}}/rutina
Content-Type: application/json

{
    "descripcion": "Recomendaciones para leer mas",
    "name": "Como leer mas",
    "urlFoto": "https://www.comunidadbaratz.com/wp-content/uploads/Leer-es-un-modo-de-entretenimiento-y-conocimiento-que-desde-hace-tiempo-convive-y-compite-contra-otras-formas-de-ocio-e-informacion.jpg",
    "urlVideo": "https://m.elmostrador.cl/cultura/2020/08/20/diez-trucos-para-leer-mas/"
    }    

### TEMPLATETODO POST
POST {{host}}/templatetodo
Content-Type: application/json

{
    "name": "Template To Do3",
	"idDia": null
    }    

### RECETAS POST
POST {{host}}/recetas
Content-Type: application/json

{
    "descripcion": "dga",
    "name": "Receta 3",
    "urlFoto": "sdga",
    "urlVideo": "asdga"
    }    

#los campos son en su mayoria unicos    

### TODOUSUARIO POST
POST {{host}}/todousuario
Content-Type: application/json

{
    "date": "2021-08-24",
	"desafioID": 1,
    "done": false,
	"userID": 1
    }