@host=https://3001-bronze-impala-vib65y6n.ws-us16.gitpod.io
#puedo definir variables, en este caso host
#para luego definir los metodos que quiero usar

### Creación de hash
POST {{host}}/hash
Content-Type: application/json
#aqui estoy llamando al endpoint hash de main.py 

### REGISTER
POST {{host}}/register
Content-Type: application/json

{
    "email":"conejitoretrinity@hola.cl",
    "nombre":"Conejito 2.0",
    "password":"20"
}

# {
#     "email":"la@guagua.cl",
#     "nombre":"guagua",
#     "password":"87654321"
# }




###  @AUTH
# @name authSession
POST {{host}}/login
Content-Type: application/json

{
    "email":"conejito@hola.cl",
    "password":"sdfs"
}

###
@token = {{authSession.response.body.$.token}}



### USER
GET {{host}}/users
Content-Type: application/json
#Authorization: Bearer {{token}}

#en este archivo deberian ir todas las formas 
#de inyectar cada uno de los endpoints

### DESAFIO POST
POST {{host}}/desafios
Content-Type: application/json

{
    "nombreDesafio": "Desafio 2",
    "descripcionDesafio": "Descripcion larga del desafio 2",
    "feat1": "feature 1",
    "feat2": "feature 2",
    "feat3": "feature 3",
    "photoURL": "http://cdn2.dineroenimagen.com/media/dinero/styles/xlarge/public/images/2019/12/knowledge-10520101920.jpg"
    }

#los campos son en su mayoria unicos

### DIAS POST
POST {{host}}/dias
Content-Type: application/json

{
    "numeroDia": 3,
    "idDesafio": null
}

### EXTRA POST (Receta o rutina)
POST {{host}}/extras
Content-Type: application/json

{
    "actividad": "Nombre_actividad",
    "tipo": "Rutina",
    "descripcion": "Descripcion larga",
    "urlFoto": "https://www.comunidadbaratz.com/wp-content/uploads/Leer-es-un-modo-de-entretenimiento-y-conocimiento-que-desde-hace-tiempo-convive-y-compite-contra-otras-formas-de-ocio-e-informacion.jpg",
    "urlVideo": "https://m.elmostrador.cl/cultura/2020/08/20/diez-trucos-para-leer-mas/",
    "dia": "1"
    }    

### TEMPLATETODO POST
POST {{host}}/templatetodo
Content-Type: application/json

{
    "name": "Template To Do3",
	"idDia": null
    }    

### TODOUSUARIO POST
POST {{host}}/todousuario
Content-Type: application/json

{
    "actividad": "lavar ropa2",
    "done": false,
    "fecha": "2021-08-25",
    "userID": 2
    }
