"""empty message

Revision ID: 22d42a2b06da
Revises: c541a224fe37
Create Date: 2021-08-21 15:34:19.459699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22d42a2b06da'
down_revision = 'c541a224fe37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolog', sa.Column('todoID', sa.Integer(), nullable=True))
    op.drop_constraint('todolog_ibfk_1', 'todolog', type_='foreignkey')
    op.create_foreign_key(None, 'todolog', 'templatetodo', ['todoID'], ['id'])
    op.drop_column('todolog', 'desafioID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolog', sa.Column('desafioID', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todolog', type_='foreignkey')
    op.create_foreign_key('todolog_ibfk_1', 'todolog', 'desafios', ['desafioID'], ['id'])
    op.drop_column('todolog', 'todoID')
    # ### end Alembic commands ###
