"""empty message

Revision ID: 2847a4c40190
Revises: 3b2c539ed1e9
Create Date: 2021-08-19 18:08:25.600290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2847a4c40190'
down_revision = '3b2c539ed1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('urlFoto', table_name='rutina')
    op.drop_index('urlFoto_2', table_name='rutina')
    op.drop_index('urlVideo', table_name='rutina')
    op.drop_index('urlVideo_2', table_name='rutina')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('urlVideo_2', 'rutina', ['urlVideo'], unique=False)
    op.create_index('urlVideo', 'rutina', ['urlVideo'], unique=False)
    op.create_index('urlFoto_2', 'rutina', ['urlFoto'], unique=False)
    op.create_index('urlFoto', 'rutina', ['urlFoto'], unique=False)
    # ### end Alembic commands ###
