"""empty message

Revision ID: 363f4896213b
Revises: 
Create Date: 2021-08-18 22:19:16.859555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363f4896213b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('videoUrl', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('imagen'),
    sa.UniqueConstraint('imagen'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('videoUrl'),
    sa.UniqueConstraint('videoUrl')
    )
    op.create_table('rutina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('videoUrl', sa.String(length=250), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('imagen'),
    sa.UniqueConstraint('imagen'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('videoUrl'),
    sa.UniqueConstraint('videoUrl')
    )
    op.create_table('templatetodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('todo1', sa.String(length=80), nullable=False),
    sa.Column('todo2', sa.String(length=80), nullable=False),
    sa.Column('todo3', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('todo1'),
    sa.UniqueConstraint('todo1'),
    sa.UniqueConstraint('todo2'),
    sa.UniqueConstraint('todo2'),
    sa.UniqueConstraint('todo3'),
    sa.UniqueConstraint('todo3')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('idRecetas', sa.Integer(), nullable=False),
    sa.Column('idTemplateTodo', sa.Integer(), nullable=False),
    sa.Column('idRutina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idRecetas'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['idRutina'], ['rutina.id'], ),
    sa.ForeignKeyConstraint(['idTemplateTodo'], ['templatetodo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('todo', sa.String(length=120), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('todo'),
    sa.UniqueConstraint('todo')
    )
    op.create_table('desafios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('dificultad', sa.String(length=80), nullable=False),
    sa.Column('feat1', sa.String(length=120), nullable=False),
    sa.Column('feat2', sa.String(length=120), nullable=False),
    sa.Column('feat3', sa.String(length=120), nullable=False),
    sa.Column('idDias', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idDias'], ['dias.id'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('dificultad'),
    sa.UniqueConstraint('dificultad'),
    sa.UniqueConstraint('feat1'),
    sa.UniqueConstraint('feat1'),
    sa.UniqueConstraint('feat2'),
    sa.UniqueConstraint('feat2'),
    sa.UniqueConstraint('feat3'),
    sa.UniqueConstraint('feat3'),
    sa.UniqueConstraint('imagen'),
    sa.UniqueConstraint('imagen'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desafios')
    op.drop_table('todo')
    op.drop_table('dias')
    op.drop_table('user')
    op.drop_table('templatetodo')
    op.drop_table('rutina')
    op.drop_table('recetas')
    # ### end Alembic commands ###
