"""empty message

Revision ID: 38620bd09f3a
Revises: 435ad0e1c7b0
Create Date: 2021-08-28 03:16:23.714936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38620bd09f3a'
down_revision = '435ad0e1c7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_extrasusuarios_userID'), 'extrasusuarios', ['userID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extrasusuarios_userID'), table_name='extrasusuarios')
    # ### end Alembic commands ###
