"""empty message

Revision ID: 3b2c539ed1e9
Revises: e74cbae4fc7f
Create Date: 2021-08-19 18:04:00.874779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b2c539ed1e9'
down_revision = 'e74cbae4fc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dias', 'idReceta',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('dias', 'idRutina',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dias', 'idRutina',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('dias', 'idReceta',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
