"""empty message

Revision ID: 435ad0e1c7b0
Revises: 8c19eb084438
Create Date: 2021-08-27 19:07:43.941793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435ad0e1c7b0'
down_revision = '8c19eb084438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='templatetodo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'templatetodo', ['name'], unique=False)
    # ### end Alembic commands ###
