"""empty message

Revision ID: 67060c78f46b
Revises: b3da5bf9d69d
Create Date: 2021-08-29 16:35:48.236042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67060c78f46b'
down_revision = 'b3da5bf9d69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extrasusuarios', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('todousuario', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todousuario', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('extrasusuarios', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
