"""empty message

Revision ID: 67834fcff931
Revises: ab92eb899c7b
Create Date: 2021-08-29 17:01:56.976426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67834fcff931'
down_revision = 'ab92eb899c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('actividad', table_name='extras')
    op.drop_index('descripcion', table_name='extras')
    op.drop_index('urlFoto', table_name='extras')
    op.drop_index('urlVideo', table_name='extras')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('urlVideo', 'extras', ['urlVideo'], unique=False)
    op.create_index('urlFoto', 'extras', ['urlFoto'], unique=False)
    op.create_index('descripcion', 'extras', ['descripcion'], unique=False)
    op.create_index('actividad', 'extras', ['actividad'], unique=False)
    # ### end Alembic commands ###
