"""empty message

Revision ID: 8c19eb084438
Revises: 787f9aa1d9bc
Create Date: 2021-08-27 18:55:54.409233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c19eb084438'
down_revision = '787f9aa1d9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('feat1', table_name='desafios')
    op.drop_index('feat2', table_name='desafios')
    op.drop_index('feat3', table_name='desafios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('feat3', 'desafios', ['feat3'], unique=False)
    op.create_index('feat2', 'desafios', ['feat2'], unique=False)
    op.create_index('feat1', 'desafios', ['feat1'], unique=False)
    # ### end Alembic commands ###
