"""empty message

Revision ID: b3da5bf9d69d
Revises: 38620bd09f3a
Create Date: 2021-08-28 15:35:19.149126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3da5bf9d69d'
down_revision = '38620bd09f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('duracion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'duracion')
    # ### end Alembic commands ###
