"""empty message

Revision ID: cf6118fe0272
Revises: 
Create Date: 2021-08-31 20:40:43.597305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6118fe0272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desafios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreDesafio', sa.String(length=80), nullable=False),
    sa.Column('descripcionDesafio', sa.String(length=250), nullable=False),
    sa.Column('feat1', sa.String(length=120), nullable=False),
    sa.Column('feat2', sa.String(length=120), nullable=False),
    sa.Column('feat3', sa.String(length=120), nullable=False),
    sa.Column('photoURL', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcionDesafio'),
    sa.UniqueConstraint('nombreDesafio'),
    sa.UniqueConstraint('photoURL')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=9000), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('desafio', sa.String(length=80), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numeroDia', sa.Integer(), nullable=False),
    sa.Column('idDesafio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDesafio'], ['desafios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extrasusuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('actividad', sa.String(length=150), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('URLVideo', sa.String(length=200), nullable=True),
    sa.Column('URLFoto', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extrasusuarios_userID'), 'extrasusuarios', ['userID'], unique=False)
    op.create_table('todousuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('actividad', sa.String(length=150), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('urlVideo', sa.String(length=250), nullable=False),
    sa.Column('urlFoto', sa.String(length=250), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dia'], ['dias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templatetodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('idDia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDia'], ['dias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templatetodo')
    op.drop_table('extras')
    op.drop_table('todousuario')
    op.drop_index(op.f('ix_extrasusuarios_userID'), table_name='extrasusuarios')
    op.drop_table('extrasusuarios')
    op.drop_table('dias')
    op.drop_table('user')
    op.drop_table('desafios')
    # ### end Alembic commands ###
