"""empty message

Revision ID: d3208a6750bf
Revises: 67060c78f46b
Create Date: 2021-08-29 16:37:22.027812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3208a6750bf'
down_revision = '67060c78f46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extrasusuarios', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('todousuario', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todousuario', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('extrasusuarios', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
