"""empty message

Revision ID: e74cbae4fc7f
Revises: 528afde3a65b
Create Date: 2021-08-19 17:14:20.594713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e74cbae4fc7f'
down_revision = '528afde3a65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dias', 'idDesafio',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dias', 'idDesafio',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
